#!/bin/bash
# install.sh — 安装 ai-hooks 为全局命令
#
# 用法:
#   bash install.sh                   # 安装到 ~/.local/bin (Linux/macOS)
#   bash install.sh --prefix ~/bin    # 安装到指定目录
#   bash install.sh --user            # 安装到用户目录 (Windows: %APPDATA%)
#
# 安装后可在终端直接使用:
#   ai-init <project-dir>
#   ai-doctor <project-dir>
#   ai-update <project-dir>
#   ai-uninstall <project-dir>

set -euo pipefail

HOOKS_DIR="$(cd "$(dirname "$0")" && pwd)"

# Windows Git Bash 路径归一化: /f/xxx → F:/xxx
case "$HOOKS_DIR" in
  /[a-zA-Z]/*)
    d=$(echo "$HOOKS_DIR" | cut -d/ -f2 | tr '[:lower:]' '[:upper:]')
    r=$(echo "$HOOKS_DIR" | cut -d/ -f3-)
    HOOKS_DIR="${d}:/${r}"
    ;;
esac

# ── 目标安装目录 ──
detect_bin_dir() {
    # 1. 如果指定了 --prefix
    if [ -n "${PREFIX:-}" ]; then
        echo "$PREFIX"
        return
    fi

    # 2. Windows: %APPDATA%/ai-hooks/bin
    if [ -n "${APPDATA:-}" ] && [ -d "$APPDATA" ]; then
        echo "$APPDATA/ai-hooks/bin"
        return
    fi

    # 3. ~/.local/bin (Linux/macOS, 通常已在 PATH)
    if [ -d "$HOME/.local/bin" ] 2>/dev/null; then
        echo "$HOME/.local/bin"
        return
    fi

    # 4. ~/bin
    if [ -d "$HOME/bin" ] 2>/dev/null; then
        echo "$HOME/bin"
        return
    fi

    # 5. 保底
    mkdir -p "$HOME/.local/bin" 2>/dev/null || true
    echo "$HOME/.local/bin"
}

# 解析参数
PREFIX=""
while [ $# -gt 0 ]; do
    case "$1" in
        --prefix) PREFIX="$2"; shift 2 ;;
        --user) PREFIX="${APPDATA:-$HOME}/ai-hooks/bin"; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

BIN_DIR="$(detect_bin_dir)"
mkdir -p "$BIN_DIR"

# ── 创建包装脚本 ──
create_wrapper() {
    local name="$1"
    local target="$2"
    local wrapper="$BIN_DIR/$name"

    cat > "$wrapper" << WRAPPER
#!/bin/bash
# ai-hooks: $name — auto-generated by install.sh
export AI_HOOKS_DIR="$HOOKS_DIR"
export AI_HOOKS_PYTHON="\${AI_HOOKS_PYTHON:-python}"
exec bash "\$AI_HOOKS_DIR/$target" "\$@"
WRAPPER
    chmod +x "$wrapper"
    echo "  [OK] $BIN_DIR/$name → $target"
}

echo "=== ai-hooks install ==="
echo "安装到: $BIN_DIR"
echo ""

create_wrapper "ai-init"      "setup.sh"
create_wrapper "ai-doctor"    "doctor.sh"
create_wrapper "ai-update"    "update.sh"
create_wrapper "ai-uninstall" "uninstall.sh"
create_wrapper "ai-log"       "bin/ai-log"

echo ""
echo "=== 完成 ==="
echo ""
echo "ai-hooks 已安装到: $BIN_DIR"
echo ""

# 检查 PATH
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:" 2>/dev/null; then
    echo "⚠  $BIN_DIR 不在 PATH 中"
    echo "   请将以下内容添加到你的 shell 配置 (~/.bashrc / ~/.zshrc / ~/.bash_profile):"
    echo ""
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
    echo ""
fi

echo "用法:"
echo "  ai-init ~/my-new-project     — 新项目接入"
echo "  ai-doctor ~/my-project       — 诊断"
echo "  ai-update ~/my-project       — 升级"
echo "  ai-uninstall ~/my-project    — 卸载"
echo ""
echo "环境变量:"
echo "  AI_HOOKS_PYTHON=python3  ai-init ~/project   — 指定 Python"
